apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      targetPort: 3000
      port: 8000
      nodePort: 30008
  selector:
    app: myapp